apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: example-container
    image: nginx






#   GNU nano 6.3                                 redis-definition.yaml                                            
# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     run: redis
#   name: redis
# spec:
#   containers:
#   - image: redis123
#     name: redis

